
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-web-app-deployment
  labels:
    app: spring-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-web-app
  template:
    metadata:
      labels:
        app: spring-web-app
    spec:
      containers:
      - name: spring-web-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        
---

kind: Service
apiVersion: v1
metadata:
  name: spring-web-app
spec:
  type: NodePort
  selector:
    app: spring-web-app
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081
